---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Homepage 🏡

# looks & operations
background:
    image: https://wallpapercave.com/wp/wp9668133.jpg
    opacity: 80

theme: dark # or light

cardBlur: xs # xs, md, etc... see https://tailwindcss.com/docs/backdrop-blur

layout:
  - Server Management:
  - Development:
  - Other Containers:
      style: row
      columns: 3

headerStyle: boxedWidgets

showStats: true
statusStyle: "dot"

target: _blank # Possible options include _blank, _self, and _top
